### ISSUE TITLE
workareas-changed signal is emitted "randomly", and makes the dock to be shown

### ISSUE THREAD

**Issue by rastersoft** [fthx/dock-from-dash#35] opened 2022-04-01 23:21 UTC
I have found that the dock, sometimes, shows "randomly" without I triggering it. After several tests, I found that the problem is that the "workareas-changed" signal is emitted sometimes when a new window is added or removed, and that forces the dock to show up.

The point is that I don't understand why are you using that signal...

**Comment by rastersoft** [comment] 2022-04-01 23:45
Ok, now I see it: you use it to set the size and location of the dock.

I uploaded a MR that fixes this and other things.

**Comment by fthx** [comment] 2022-04-02 07:32
Yes I do use this to detect resolution or monitor changes.
There are caveats here and I took a lot of time  to make it work reliably: e.g. triggering the overview allows the position to be really updated, for whatever GS signals update tricks.

**Comment by fthx** [comment] 2022-04-02 07:38
There is a hide/show trick to trigger the position to be updated, too...

**Comment by fthx** [comment] 2022-04-02 07:39
Note that I never experienced this bug!

**Comment by fthx** [comment] 2022-04-02 07:55
https://github.com/fthx/dock-from-dash/commit/f99376f179e62f06bf653fb3c1faaf6f8eed7997
I'll look at the background bug, using 'always show'. I'll see if it happens once. (Was on X11? I do always use Wayland, even for tests so I cannot see this, if applicable).

**Comment by fthx** [comment] 2022-04-02 08:11
Could you tell me how to reproduce, even if it's random?

**Comment by rastersoft** [comment] 2022-04-02 12:51
It happens sometimes when I have three maximized windows in three workspaces, I close the last window (the one in the third workspace) and switch to the second: sometimes it is triggered there.

**Comment by rastersoft** [comment] 2022-04-02 12:51
I use wayland, BTW.

**Comment by fthx** [comment] 2022-04-02 20:43
Yes I can reproduce easily now.
Just open a full screen w.
Go to 2nd ws.
Open a new full screen w.
The signal is emitted.

I have an idea to workaround this bug in GS.

**Comment by rastersoft** [comment] 2022-04-02 20:55
The old MR did a workaround by storing the size of the workspaces and comparing the new values with the old ones.

Anyway, maybe you should also separate the show part of the resize part.

**Comment by fthx** [comment] 2022-04-02 21:10
really closed this time by:
https://github.com/fthx/dock-from-dash/commit/db100649d3c70491115bde25b528e5e7b38ede6c

**Comment by fthx** [comment] 2022-04-02 21:15
> Anyway, maybe you should also separate the show part of the resize part.

It's possible but don't forget that dock has to be triggered one to make its position really updated in all situations.
I'll be happy here if there is a smarter && shorter solution, but variables and signals in GS are sometimes lazy. It has to be teste when plugging in/out an external monitor, e.g.

**Comment by rastersoft** [comment] 2022-04-02 21:23
But you can just update the size/position and avoid showing it...

**Comment by rastersoft** [comment] 2022-04-02 21:24
(also, remember that sometimes you need to use "connect_after" instead of "connect"...)

**Comment by fthx** [comment] 2022-04-02 21:30
If a connect_after (that I never used before) do avoid to trigger the dock (with show/hide trick), I'll be happy but it needs some tests because if we go for simply remove this trigger part, it won't update position correctly in all cases.
What signal should I connect_after rather than connect?

**Comment by rastersoft** [comment] 2022-04-02 21:41
I was talking about other signals, like "realize", where if you connect using "connect", you receive it "when the widget is going to be created in screen", but if you connect using "connect_after", you receive it "immediately after being created in the screen".

In this case, I think that you should separate dock_refresh() in two functions: one from line 189 to line 203, and another from line 204 to the end, and call the first one only when the size must be updated, and the second one only when the dock has to be presented on screen.

Also, I would connect _screen_border_box_refresh() to the "allocation-changed" signal of the dock; this way, every time the dock changes its size, the border box would also change it.

**Comment by fthx** [comment] 2022-04-03 09:57
https://github.com/fthx/dock-from-dash/commit/cdadc7eab277393d6c48df65d1d1bde4fd73f375
We have to check if this version is reliable, especially for screen border box update when areas do change.

**Comment by fthx** [comment] 2022-04-03 09:58
> Also, I would connect _screen_border_box_refresh() to the "allocation-changed" signal of the dock; this way, every time the dock changes its size, the border box would also change it.

This does not work, as far as I tested.

**Comment by rastersoft** [comment] 2022-04-03 10:59
Yes, I don't know why, but I receive an error if I try to connect to "allocation-changed"... which is odd.

But you can connect to "notify::width" and "notify::height" to the _box element, and use that to set the width and the height of the border box. I tested it and it does work.

**Comment by fthx** [comment] 2022-04-03 11:10
Could you have a look at latest code here?

I've got one issue (only one?) here:

```
if (settings.get_boolean('always-show')) {
            this.set_position(this.work_area.x, this.work_area.y + this.work_area.height - this.height);
        } else {
            this.set_position(this.work_area.x, this.work_area.y + this.work_area.height);
        }
```

(line 146)

It does not work. The dock does not appear (autohide enabled). If I do simply:
`            this.set_position(this.work_area.x, this.work_area.y + this.work_area.height - this.height);`
instead of this 'if' statement, it works but after a workareas refresh (toggled by GS bug) the position of the dock is 'shown position', so the animation is instant and that does not look clean.

**Comment by fthx** [comment] 2022-04-03 11:10
If you're ok with that, we could look at the screenbox update with signal after having solved all the others known issues?

**Comment by rastersoft** [comment] 2022-04-03 11:15
Mmm... I think that you are forgetting that the values of width and height aren't set from the beginning, but are being updated regularly based on constraints and the size of inner elements, so precisely connecting to the notify::width and notify::height signals and calling there a function that updates the position of the dock based on the current values is the only way of ensuring that everything works as expected.

**Comment by rastersoft** [comment] 2022-04-03 11:16
Remember that any element begins with a size of 0x0, and only when it is realized are all its children called recursively to calculate the final size.

**Comment by fthx** [comment] 2022-04-03 11:21
Ok but why in this case the one-line solution:
` this.set_position(this.work_area.x, this.work_area.y + this.work_area.height - this.height);`
does work?

**Comment by rastersoft** [comment] 2022-04-03 11:39
Maybe because the border box isn't set correctly...?

**Comment by fthx** [comment] 2022-04-03 12:14
But it is, if I just put the single command.
I'm working on signals to update screen box, following your test.

**Comment by fthx** [comment] 2022-04-03 12:58
I think this one is now good:
https://github.com/fthx/dock-from-dash/commit/fc66e4d5b208c5bee8d75244ca3a30b9eaf01bab

**Comment by fthx** [comment] 2022-04-03 13:11
the first position of the shown dock is not correct (seen better in always show mode).
That's a problem I had a long time ago, and that's why I did use a show/hide trick.

If you have a solution?

**Comment by fthx** [comment] 2022-04-03 19:43
https://github.com/fthx/dock-from-dash/commit/ba5c308e0d1c1f91792c41eb2abdae9900809ceb

Finally?...

**Comment by rastersoft** [comment] 2022-04-03 19:45
I'll test it, give me some time.

**Comment by fthx** [comment] 2022-04-03 19:47
Oh, that's not ok with always mode on.
I maybe think we could remove this mode...

**Comment by rastersoft** [comment] 2022-04-03 20:27
I think that the code is quite complex... I would do the following:

- set a flag in the dock specifying if it is currently being showed (or being animated to be showed) or hided (or being animated to be hided).
- create one function that returns whether the dock should be showing or hided. There I put all the possible conditions (the mouse is hovering the dock, the border bar, the "keep fixed" setting, the "show the dock during startup"...)
- create one function that, when called, compares the current state of the flag with the one returned by the function, and if it is different, cancels any animation being done and do the new animation, changing the flag.
- call that last function from any event that could change the visibility status of the dock

This way all the code is in a single place and is easier to keep track of all the possible cases...

**Comment by fthx** [comment] 2022-04-04 07:04
https://github.com/fthx/dock-from-dash/commit/9172ebd6fbf1a60b5e2fce9551dd4e13d0c39549

**Closed by fthx** 2022-04-04 07:04 UTC
Labels: not-my-fault-ask-gnome-devs

**Comment by rastersoft** [comment] 2022-04-04 07:55
I'll try it today

**Comment by rastersoft** [comment] 2022-04-04 11:55
There's still a problem: if there is no window in the current workspace, clicking on an icon makes the dock disappear. Only if there is already a window of another program will the dock remain after clicking.

**Comment by fthx** [comment] 2022-04-04 12:28
https://github.com/fthx/dock-from-dash/commit/0cdc4587b016cdab58f02ebe1b9881b37552096d

**Comment by fthx** [comment] 2022-04-04 12:29
GS extensions server is down but i'll push this soon.

**Comment by rastersoft** [comment] 2022-04-04 12:37
It seems to be fixed now.
