### ISSUE TITLE
Intellihide

### ISSUE THREAD

**Issue by FranJavier99** [fthx/dock-from-dash#43] opened 2022-04-11 05:02 UTC
being on the screen without open windows it stays hidden, would there be a way to show and hide it when it is superimposed by a window?

**Comment by fthx** [comment] 2022-04-11 05:43
Duplicate of closed
https://github.com/fthx/dock-from-dash/issues/4

We won't do that, atm at least. That's a complex feature that introduces a lot of code and a lot of bugs.
We focus now on stability.

**Closed by fthx** 2022-04-11 05:43 UTC
Labels: wishlist
