### ISSUE TITLE
Sometimes the first click won't be registered

### ISSUE THREAD

**Issue by miguelcanosantana** [fthx/dock-from-dash#8] opened 2022-01-10 23:25 UTC
Like the title says I'm having a little problem. When the dock is on the desktop, when I try to click the apps menu, sometimes I need to do it twice because the first time won't work.

Should I send any logs or something? (I don't know how to). Thanks

**Comment by fthx** [comment] 2022-01-11 08:43
I never did experience any issue with this click.
Do you use a special config? (touchscreen, etc.)
Do you have a way to reproduce?
Do you have any error in logs ("js")?

**Comment by fthx** [comment] 2022-01-12 21:18
Feel free to reopen if needed!

**Comment by fthx** [comment] 2022-02-06 18:29
I suspect that the app state is still flagged as running by GS but not updated here:
https://github.com/fthx/dock-from-dash/blob/1ceb8dcb3fb64f68309fb085efc860c29e088243/extension.js#L70

If this is the *first* click on the app in your session, that's quite odd because code should enter app's activation.

**Comment by fthx** [comment] 2022-02-06 20:47
Tell me if it's ok after this:
https://github.com/fthx/dock-from-dash/commit/61af1309709e1239dd44f11c89187aa23ede679b
(will be included in v22 update)

**Comment by fthx** [comment] 2022-02-06 21:03
I was searching another trick but found this:
https://github.com/micheleg/dash-to-dock/blob/53114b4e000482a753e8b42dfa10d6057c08d1c6/appIcons.js#L664-L671
maybe related?

**Comment by fthx** [comment] 2022-03-01 20:10
I think this issue is solved by v28.
Reopen if needed, of course.

The solution implies an overview trick.

**Closed by fthx** 2022-03-01 20:10 UTC
Labels: needs info
